### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by utkarsh2102** [expressjs/serve-index#89]
Hey,

There seems to be a failing test.

```
  1 failing

  1) serveIndex(root)
       should treat an ENAMETOOLONG as a 414:
     Error: expected 414 "URI Too Long", got 400 "Bad Request"
      at Test.assert (/usr/lib/nodejs/supertest/lib/test.js:205:15)
      at Server.assert (/usr/lib/nodejs/supertest/lib/test.js:132:12)
      at emitCloseNT (net.js:1629:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dougwilson** [comment]
Hi @utkarsh2102 sorry I haven't been watching this repo (fixed now, I subscribed for notifications -- oops!). Yes, this was an issue for Node.js 10+ due to the change in allowed HTTP header size (and thus URL size). The `master` branch has this resolved, though. It was just an issue with the tests, so no release was made.

Sorry for any confusion!
