### ISSUE TITLE
How to custom handle ForbiddenError: Forbidden with malicious path traversal characters

### ISSUE THREAD

**Issue by Cerlancism** [expressjs/serve-index#97]
I tried to test how this handles path traversal vulnerability, fortunately it gives forbidden error. However, it sends the entire tracktrace to the client. How to disable this behaviour?

```js
import express from 'express';
import serveIndex from 'serve-index'

const PORT = 80
const app = express()
app.use(serveIndex('public'))
app.listen(PORT, () => console.log("server listening", PORT))
```
Then
`http://localhost/..%2F` in browser

```
ForbiddenError: Forbidden
    at C:\Users\CHE-Main\Desktop\node-hello\node_modules\serve-index\index.js:125:19
    at Layer.handle [as handle_request] (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\index.js:275:10)
    at next (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\route.js:127:14)
    at next (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\CHE-Main\Desktop\node-hello\node_modules\express\lib\router\route.js:131:14)
```

**Comment by dougwilson** [comment]
http://expressjs.com/en/guide/error-handling.html#the-default-error-handler
